[package]
name = "entreprise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.mongodb]
version = "2.7.1"
default-features = false
features = ["async-std", "tokio-sync"]